### ISSUE TITLE
Build the frontend interface for meal tracking.

### ISSUE THREAD

**Issue by Ayush243871** [Ayush243871/Eco_Data_Drivers_028#10]
- [x] Build the frontend interface for meal tracking.
- [x] Implement date picker for meal tracking by day.
- [x] Display meal history in a table or list.
- [x] Search functionality for user to search for different foods containing how much nutrient
